// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Prisma 7 removed datasource.directUrl; the CLI uses datasource.url for
  // migrations, so point url at the DIRECT (non-pooled) endpoint and fall back to
  // DATABASE_URL. (This unknown property broke every build from v26 onward.)
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
