/**
 * report-extraction.ts — §1.2. "Report before building."
 *
 * How many distinct citations, how many pre-2003, the top 200 by citing-document count, the ten most
 * common malformed matches — and **twenty extracted citations printed in full alongside the sentence
 * they came from**, because if the parser is wrong that is where it shows, not in a count.
 *
 * ⚠ THE MALFORMED LIST IS NOT AUTOMATIC AND DOES NOT PRETEND TO BE. There is no oracle for "this
 * regex match is not a case". What this does is rank the strongest CANDIDATES — high-frequency
 * matches beside which no case name was ever observed — and print their sentences so a person
 * decides. A list of "malformed matches" generated by the same logic that made the matches would be
 * the check that cannot fail, one step along.
 *
 * Usage: tsx caseref/report-extraction.ts [--top=200]
 */
import fs from 'fs'
import path from 'path'
import { OUT } from '../c2/db'

const arg = (k: string) => (process.argv.find((a) => a.startsWith(`--${k}=`)) ?? '').split('=')[1] || null
const TOP = parseInt(arg('top') ?? '200', 10)
const n = (x: number) => x.toLocaleString('en-GB')

interface Agg {
  citation: string; kind: string; year: number; series: string
  docs: number; byCorpus: Record<string, number>; names: Record<string, number>
  samples: Array<{ id: string; corpus: string; sentence: string; raw: string }>
}

function main() {
  const full = path.join(OUT, 'CASEREF_citations.jsonl')
  const pilot = path.join(OUT, 'CASEREF_citations.pilot.jsonl')
  const src = fs.existsSync(full) ? full : pilot
  const all: Agg[] = fs.readFileSync(src, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l))
  console.log(`source: ${path.basename(src)}   (${n(all.length)} distinct citations)\n`)

  // ── 1. the shape of what came out
  const pre2003 = all.filter((a) => a.year < 2003)
  const neutral = all.filter((a) => a.kind === 'neutral')
  const lawrep = all.filter((a) => a.kind === 'law-report')
  console.log('══ HOW MANY, AND OF WHAT KIND ══')
  console.log(`   distinct citations           ${n(all.length)}`)
  console.log(`   pre-2003                     ${n(pre2003.length)}  (${(pre2003.length / all.length * 100).toFixed(1)}%)`)
  console.log(`   neutral (2001 on)            ${n(neutral.length)}`)
  console.log(`   law report (the only form a pre-2001 case has)   ${n(lawrep.length)}`)
  console.log(`   citing-document total        ${n(all.reduce((s, a) => s + a.docs, 0))}`)

  const byDecade = new Map<number, number>()
  for (const a of all) { const d = Math.floor(a.year / 10) * 10; byDecade.set(d, (byDecade.get(d) ?? 0) + 1) }
  console.log('\n   by decade:')
  for (const [d, c] of [...byDecade].sort((a, b) => a[0] - b[0])) {
    if (c < 5) continue
    console.log(`      ${d}s  ${String(c).padStart(6)}  ${'█'.repeat(Math.round(c / Math.max(...byDecade.values()) * 40))}`)
  }

  const bySeries = new Map<string, number>()
  for (const a of all) bySeries.set(a.series, (bySeries.get(a.series) ?? 0) + 1)
  console.log('\n   top 15 series / courts:')
  for (const [s, c] of [...bySeries].sort((a, b) => b[1] - a[1]).slice(0, 15)) console.log(`      ${String(c).padStart(6)}  ${s}`)

  // ── 2. the top N by citing documents
  const top = [...all].sort((a, b) => b.docs - a.docs).slice(0, TOP)
  console.log(`\n══ TOP 30 OF THE TOP ${TOP}, BY CITING DOCUMENTS ══`)
  for (const a of top.slice(0, 30)) {
    const name = Object.entries(a.names).sort((x, y) => y[1] - x[1])[0]?.[0] ?? '(no name observed)'
    console.log(`   ${String(a.docs).padStart(5)}  ${a.citation.padEnd(22)} ${name.slice(0, 56)}`)
  }

  // ── 3. §1.2's own instruction: twenty citations printed WITH THE SENTENCE
  console.log('\n══ TWENTY EXTRACTED CITATIONS, IN FULL, WITH THE SENTENCE THEY CAME FROM ══')
  console.log('   (ten of the most-cited, then ten drawn evenly across the whole list — so this is')
  console.log('    not twenty easy ones)\n')
  const step = Math.max(1, Math.floor(all.length / 10))
  const sample = [...top.slice(0, 10), ...all.filter((_, i) => i % step === 0).slice(0, 10)]
  for (const a of sample) {
    const s = a.samples[0]
    if (!s) continue
    const name = Object.entries(a.names).sort((x, y) => y[1] - x[1])[0]?.[0]
    console.log(`── ${a.citation}   [${a.kind}, ${a.year}]   cited in ${n(a.docs)} document${a.docs === 1 ? '' : 's'}`)
    console.log(`   name observed : ${name ?? '(none — recorded as unnamed, never guessed)'}`)
    console.log(`   matched text  : "${s.raw}"`)
    console.log(`   in            : ${s.corpus} ${s.id}`)
    console.log(`   sentence      : ${s.sentence.slice(0, 300)}`)
    console.log('')
  }

  // ── 4. the strongest candidates for a wrong match
  console.log('══ TEN STRONGEST CANDIDATES FOR A MALFORMED MATCH ══')
  console.log('   Ranked by: frequently matched, and NO case name ever seen beside it. A real')
  console.log('   authority is named by somebody eventually; a regex artefact never is.\n')
  const suspicious = all
    .filter((a) => Object.keys(a.names).length === 0 && a.docs >= 2)
    .sort((a, b) => b.docs - a.docs)
    .slice(0, 10)
  if (!suspicious.length) console.log('   none — every frequently-matched citation has a name beside it somewhere.')
  for (const a of suspicious) {
    console.log(`── ${a.citation.padEnd(22)} ${n(a.docs)} documents, no name ever observed`)
    console.log(`   sentence: ${a.samples[0]?.sentence.slice(0, 260) ?? '(no sample)'}`)
    console.log('')
  }

  fs.writeFileSync(path.join(OUT, 'CASEREF_extraction_report.json'), JSON.stringify({
    generated: new Date().toISOString(), source: path.basename(src),
    distinct: all.length, pre2003: pre2003.length, neutral: neutral.length, lawReport: lawrep.length,
    citingDocumentTotal: all.reduce((s, a) => s + a.docs, 0),
    byDecade: Object.fromEntries(byDecade), bySeries: Object.fromEntries(bySeries),
    top: top.map((a) => ({ citation: a.citation, docs: a.docs, year: a.year, kind: a.kind, name: Object.entries(a.names).sort((x, y) => y[1] - x[1])[0]?.[0] ?? null })),
    malformedCandidates: suspicious,
  }, null, 2))
  console.log('written: docs/census/CASEREF_extraction_report.json')
}
main()
