import re
# Voice pass, part one. Exact-string replacements only - no pattern substitution
# inside prose - because a blanket replace corrupted a quotation earlier in this
# project. Each pair below was read in context first.
E = {
'02_register.md':[
 ("**What we think it means:**","**What this appears to mean:**"),
 ("**What we think it means**","**What this appears to mean**"),
 ("Our search also turned up","The search also turned up"),
 ("Our search returned","The search returned"),
 ("our reading, which may be wrong","a reading of it, which may be wrong"),
 ("The right is our best reading of what would have to change in the law to deliver it, and why we think so.",
  "The right is a reading of what would have to change in the law to deliver it, and why."),
 ("as close to David's own words as we can get it","in David's own words wherever the record allows"),
 ("Where we have read David wrongly, this is the page to correct.",
  "Where David has been read wrongly, this is the page to correct."),
 ("the single biggest obstacle we found","the single biggest obstacle identified"),
 ("We have checked it against 287 transcripts of David speaking.",
  "It has been checked against 287 transcripts of David speaking."),
 ("We have used David's words, and set the four unsourced items out separately at the end so David can confirm or delete them.",
  "David's words are used throughout, and the four unsourced items are set out separately so David can confirm or delete them."),
 ("When we put this measure through the instrument, it reached the same conclusion independently and put it in the first line of its own diagnosis:",
  "The analysis reached the same conclusion independently, and put it in the first line of the diagnosis:"),
 ("When we put this through the instrument it proposed the narrowest route",
  "The analysis proposed the narrowest route"),
 ("*That was the instrument's own choice, not something we suggested to it.*",""),
 ("That was the instrument's own choice, not something we suggested to it.",""),
 ("David mentions this once in our whole corpus","David mentions this once in the whole corpus"),
 ("We are less confident this is intended as one of the twelve than we are about the others.",
  "Confidence that this is intended as one of the twelve is lower than for the others."),
 ("We have worked it separately so the register can show what a single named body costs to deal with.",
  "It is worked separately so the register can show what a single named body costs to deal with."),
 ("and the instrument here is guidance and ministerial direction rather than legislation",
  "and the lever here is guidance and ministerial direction rather than legislation"),
 ("1 is our first attempt at what it would contain.","1 is a first attempt at what it would contain."),
],
'01_front.md':[
 ("The first thing it asks of him is to say where we have read him wrongly.",
  "The first thing it asks of him is to say where he has been read wrongly."),
 ("against our best reading of the law that would have to change",
  "against a reading of the law that would have to change"),
 ("We tested it three ways","It is tested three ways"),
 ("We work through what would have to happen — which laws, which bodies, which decisions, which obstacles — and hand it back with the questions only they can answer.",
  "Scrutinise works through what would have to happen — which laws, which bodies, which decisions, which obstacles — and hands it back with the questions only the proposers can answer."),
 ("This is the first time the instrument has been pointed at a programme this size.",
  "This is the first time Scrutinise has been pointed at a programme this size."),
 ("with the law we think would have to change and why we think so",
  "with the law that would have to change, and why"),
 ("The instrument is new and this is among the first proposals put through it.",
  "Scrutinise is new, and this is among the first proposals put through it."),
 ("Where a section misses, that is information we want.",
  "Where a section misses, saying so is the most useful correction available."),
 ("*Telling us which is which is the most useful thing a reader can do.*",""),
 ("Telling us which is which is the most useful thing a reader can do.",""),
 ("Where we are reasoning rather than citing, we say so.",
  "Where the document reasons rather than cites, it says so."),
 ("Where the record is silent, we say that too",
  "Where the record is silent, that is said too"),
 ("Our record of court judgments begins in 2003.","The record of court judgments used here begins in 2003."),
 ("and the main free database will not let us take a copy",
  "and the main free database does not permit copying"),
 ("We have no citator — the tool lawyers use to check whether a judgment has since been doubted or overruled — so we cannot confirm that none of them has been.",
  "No citator — the tool lawyers use to check whether a judgment has since been doubted or overruled — was available for this pass, so it cannot be confirmed that none of the judgments cited has been doubted or overruled."),
 ("Where two independent transcription systems agree, we treat the text as sound.",
  "Where two independent transcription systems agree, the text is treated as sound."),
 ('Where we say "23 Acts were cited", that means 23 in the material we retrieved — not 23 in the world.',
  'Where the document says "23 Acts were cited", that means 23 in the material retrieved — not 23 in the world.'),
],
'02_framework.md':[
 ("*All four of our independent research passes reframed the question the same way, without being asked to.*",""),
 ("All four of our independent research passes reframed the question the same way, without being asked to.",""),
 ("⚠ *Names and works below are drawn from our research passes.","⚠ *Names and works below are drawn from the research."),
 ("*None has been read by us in full.*","*None has been read in full for this pass.*"),
 ("None has been read by us in full.","None has been read in full for this pass."),
],
'02a_twelve.md':[
 ("# Part 1 · The twelve, and how we chose them","# Part 1 · The twelve measures"),
 ("## The twelve measures at a glance","## The twelve measures at a glance"),
 ("**We did not take it from anyone's summary. We built it from David's own words.**",
  "**The list is not taken from anyone's summary. It is built from David's own words.**"),
 ("Where two independent transcription systems agree on a passage, we treat it as sound.",
  "Where two independent transcription systems agree on a passage, it is treated as sound."),
 ("**We checked every item on the circulated list against all 287 transcripts.",
  "**Every item on the circulated list was checked against all 287 transcripts."),
 ("## The assumptions we have made, stated so they can be rejected",
  "## The assumptions made here, stated so they can be rejected"),
 ("**One. We have treated each measure as a separate proposal.**",
  "**One. Each measure is treated as a separate proposal.**"),
 ("We have split them so that each can be worked properly — and then tested the \"must move together\" claim on its own terms in Part 3.",
  "They are split so that each can be worked properly, and the \"must move together\" claim is then tested on its own terms in Part 3."),
 ("**Two. Where David describes a complaint rather than a remedy, we have taken the complaint as the measure.**",
  "**Two. Where David describes a complaint rather than a remedy, the complaint is taken as the measure.**"),
 ("We have registered it as a measure and flagged our lower confidence.",
  "It is registered as a measure, with the lower confidence flagged."),
 ("**Three. Where David names an example rather than a target, we have worked it anyway.**",
  "**Three. Where David names an example rather than a target, it is worked anyway.**"),
 ("We have given it its own entry so the document can show what dealing with one named body actually costs.",
  "It is given its own entry so the document can show what dealing with one named body actually costs."),
 ("**Four. Where David names no legal instrument, we have not invented one for David.**",
  "**Four. Where David names no legal instrument, none is invented for him.**"),
 ("We set out the options and record that the choice is unmade.",
  "The options are set out, and the choice is recorded as unmade."),
 ("**Five. We have separated the complaint from the remedy throughout.**",
  "**Five. The complaint is separated from the remedy throughout.**"),
 ("Where we have got the complaint wrong, the entry will be wrong.",
  "Where the complaint has been got wrong, the entry will be wrong."),
 ("**Six. We have assumed the target is the law as it stands today**",
  "**Six. The target is taken to be the law as it stands today**"),
 ("## Four measures attributed to David that we could not find",
  "## Four measures attributed to David that the record does not support"),
 ("**We searched 287 transcripts and found no statement of any of them.",
  "**287 transcripts were searched, and no statement of any of them was found."),
 ("| Attributed measure | Our position |","| Attributed measure | Position |"),
],
}
tot=0
for fn,pairs in E.items():
    t=open(fn,encoding='utf-8').read(); n=0
    for a,b in pairs:
        k=t.count(a)
        if k: t=t.replace(a,b); n+=k
    t=re.sub(r'\n{4,}','\n\n\n',t) if False else t
    open(fn,'w',encoding='utf-8').write(t); tot+=n
    print(f"{fn:<24}{n:>4} replacements")
print("total",tot)
