import re
E={
'03_part2.md':[
 ("then repeal is not the instrument","then repeal is not the mechanism"),
 ("We quote this from the published version and say so.","It is quoted here from the published version."),
 ("we have no privileged access to it and imply none","no privileged access to it is claimed or implied"),
 ("**Our answer is that it does not reach the problem David has identified","**The answer is that it does not reach the problem David has identified"),
 ("It is that the instrument named for it is aimed at the wrong target.","It is that the mechanism named for it is aimed at the wrong target."),
 ("**As far as we can tell, nobody has put that in front of David or PopCon.",
  "**On the published record, nobody has put that in front of David or PopCon."),
 ("the exact provision is disputed between our reading and the Prosperity Institute's, and we have not settled it",
  "the exact provision is disputed between the reading taken here and the Prosperity Institute's, and is not settled"),
 ("We say so rather than pick one.","Both are named rather than one chosen."),
 ("**Neither side is obviously right and we do not adjudicate between them.",
  "**Neither side is obviously right, and this document does not adjudicate between them."),
 ("That is a question for David, not a conclusion of ours.","That is a question for David, not a conclusion of this document."),
 ("**A note on method, stated because it is a finding about our own process.",
  "**A note on method.**"),
 ("that our research had missed entirely, because we had researched *the law* and never asked",
  "that the research had missed entirely, because it had covered *the law* and never asked"),
 ("**The lesson is recorded here rather than hidden: this kind of sweep is cheap, high-yield, and we nearly left it out.",
  "**The lesson: this kind of sweep is cheap and high-yield."),
 ("set out so David can say what we have missed","set out so David can say what has been missed"),
 ("**The programme, as we read it**","**The programme, on this reading**"),
 ("That is a fact about the landscape a Bill would be drafted into, not a view of ours about who is right.",
  "That is a fact about the landscape a Bill would be drafted into, not a view about who is right."),
 ("and we cannot tell which from a machine transcript","and a machine transcript cannot settle which"),
 ("**This is the largest single thing our research missed, and it was found by David's own side rather than by us.**",""),
 ("This is the largest single thing our research missed, and it was found by David's own side rather than by us.",""),
 ("**The programme, as we read it, takes the whole Act in each case.",
  "**On this reading the programme takes the whole Act in each case."),
 ("**The corpus does hold Bills","**The corpus does hold Bills"),
 ("and our searches reach them","and the searches reach them"),
 ("the difference between declaring a gap we have and one we do not",
  "the difference between declaring a gap that exists and one that does not"),
 ("Two explanations are possible and we assert neither:","Two explanations are possible, and neither is asserted:"),
],
'04_part3.md':[
 ("We did, three ways.","It is tested here, three ways."),
 ("We ran the instrument twelve times, once per measure, **each run blind to the other eleven.",
  "The analysis was run twelve times, once per measure, **each run blind to the other eleven."),
 ("### ⚠⚠ Test three: what the instrument said when it disagreed","### ⚠⚠ Test three: where the analysis disagreed with the programme"),
 ("**On four of twelve measures the instrument proposed a different remedy from David's,**",
  "**On four of twelve measures the analysis proposed a different remedy from David's,**"),
 ("#### (a) Where it got there on material we did not give it","#### (a) Reached on material not supplied"),
 ("| What the instrument proposed instead |","| What was proposed instead |"),
 ("For the Bank we supplied only the Act that conferred independence.","For the Bank, only the Act that conferred independence was supplied."),
 ("For charities we supplied the *available* instruments and recorded that David names none",
  "For charities the *available* instruments were supplied, and David names none"),
 ("**the choice between them is the instrument's own.","**the choice between them was not supplied."),
 ("#### (b) Where we gave it the counter-material and it built on it","#### (b) Where the counter-material was supplied, and built on"),
 ("**We put that material into the inputs, so these four are not independent findings and are not presented as any.",
  "**That material was in the inputs, so these four are not independent findings and are not presented as any."),
 ("**given evidence that cut against the measure, the instrument did not discard it, bury it, or argue round it.",
  "**given evidence that cut against the measure, the analysis did not discard it, bury it, or argue round it."),
 ("**On four measures the instrument reached a different remedy** — on two of them from material we did not supply.",
  "**On four measures the analysis reached a different remedy** — on two of them from material that was not supplied."),
 ("**No count in this section is the instrument's reach.","**No count in this section is a limit on what can be found."),
 ("**The problem, as we stated it:**","**The problem, as stated:**"),
 ("contradicting the draft","running the other way"),
 ("**Research:**","**Evidence base:**"),
 ("Each is given with the reason the instrument gives for why it has not already been fixed.",
  "Each is given with the reason recorded for why it has not already been fixed."),
],
'06_part6_7.md':[
 ("We read David as taking the first.","David is read here as taking the first."),
 ("If that is right, repeal is not obviously the instrument.","If that is right, repeal is not obviously the mechanism."),
 ("and is legislation still the instrument for what remains?","and is legislation still the mechanism for what remains?"),
 ("**We could not find them in 287 transcripts.","**They were not found in 287 transcripts."),
 ("### And the question we most want answered","### And the question that matters most"),
 ("Where have we read David wrongly?**","Where has David been read wrongly?**"),
 ("**Every entry in the register is our reading of David's words.",
  "**Every entry in the register is a reading of David's words."),
 ("and we would rather be told now than have it printed",
  "and it is better corrected now than printed"),
 ("**Twelve separate runs of the instrument, one per measure**","**Twelve separate runs, one per measure**"),
 ("Where it cannot, we say so rather than fill the gap.","Where it cannot, that is said rather than filled."),
],
'07_bingham.md':[
 ("much of it comes from named published work rather than from our own search of the law",
  "much of it comes from named published work rather than from a search of the law"),
 ("● named independently by two or more of our four research passes, not yet checked",
  "● named independently by two or more research passes, not yet checked"),
 ("**Recommendation: this is the strongest available framing of the programme's historical case, and it is not ours — it is what all four of our independent research passes said the serious literature actually argues about.**",
  "**This is the strongest available framing of the programme's historical case, and it is not an invention of this document — it is what the serious literature actually argues about.**"),
],
'09_part5_rest.md':[
 ("We cannot assess if a new mechanism would be more viable without understanding why the current one is dormant.",
  "Whether a new mechanism would be more viable cannot be assessed without understanding why the current one is dormant."),
],
'02_register.md':[
 ("and our search returned six of its sections","and the search returned six of its sections"),
],
}
tot=0
for fn,pairs in E.items():
    t=open(fn,encoding='utf-8').read(); n=0
    for a,b in pairs:
        k=t.count(a)
        if k: t=t.replace(a,b); n+=k
    open(fn,'w',encoding='utf-8').write(t); tot+=n
    print(f"{fn:<24}{n:>4}")
print("total",tot)
