// ─────────────────────────────────────────────────────────────────────────────
// INITIAL QUESTIONS — the briefing's companion (17 Sep 2026, pilot feedback, Angus Barry).
//
// The Initial Background Briefing is "here is what we found". This is "here is what we need
// from you": everything the first pass of ONE BUILD needs from the user, grouped —
//
//   1. decisions awaiting them — the kernel fields not yet settled, and what each choice
//      rules out;
//   2. choices between causes and between candidate approaches;
//   3. what the corpus could not answer, and what kind of gap each is;
//   4. what the user knows that we do not — the testimony gaps;
//   5. challenges that need a response.
//
// ⚠⚠ EVERY ITEM STATES WHAT WOULD RESOLVE IT. 25-V §8: *"A question with no route to an
// answer is a complaint, not a question."* The route is the honest one, not a hopeful one —
// a fork is open because the corpus did NOT decide it, so what settles it is the proposer
// choosing, and promising that more searching would is a promise this product cannot keep.
// `RESOLVES` below is the one place the routes are written; `check:export` asserts every
// rendered item carries one.
//
// ⚠ IT IS STATIC, AND STAMPED WITH THE BUILD. Composed from the build's own rows the moment
// the build settles (`snapshotInitialQuestions`, called from `finishBuild`) and stored as a
// `Document` row with `buildId`/`buildVersion` — the same stamp the briefing carries, so the
// pair reads as one thing. Regeneration re-renders the stored body; it never recomposes.
// The LIVE view of the same material is the worklist in the working area (`lib/lex/agenda.ts`
// → `WorkList.tsx`); this is the record of what the build asked for, frozen.
//
// ⚠ A build that finished before this existed gets its snapshot composed on first read
// (`ensureInitialQuestions`) from its rows AS THEY STAND THEN — and the document says so,
// because a fork the user has since resolved is not "awaiting" them and the label must not
// pretend it was frozen at the build. Nothing is generated by a model anywhere in this file.
// ─────────────────────────────────────────────────────────────────────────────

import { createHash } from 'crypto'
import { prisma } from '@/lib/prisma'
import { ALL_FIELDS, PAGE_SEQUENCE } from '@/lib/lex/page1-config'
import { readKnownUnknowns } from '@/lib/lex/deepening'
import { collapseKnownUnknowns, type KnownUnknown } from '@/lib/lex/known-unknowns'
import { readableForkKey } from '@/lib/lex/reader-language'
import { BETA_MARKER } from '@/lib/lex/beta-disclosure'
import { betaBlocks } from './build-proposal'
import { markdownToBlocks } from './markdown'
import type { Block, DocumentModel } from './model'
import { ExportUnavailableError } from './build-initial-background'
import { INITIAL_QUESTIONS_NAME, INITIAL_QUESTIONS_OPENING } from './initial-background-name'

export const INITIAL_QUESTIONS_KIND = 'INITIAL_QUESTIONS'

/** Bumped when what the file SAYS changes for a reason the stored body cannot show. */
const LAYOUT_VERSION = 'v1-initial-questions'

/**
 * ⚠ THE ROUTES. One sentence per kind of item, deterministic, and honest about whose job it
 * is. Rendered at the end of every item as "What would settle it: …".
 */
export const RESOLVES = {
  fork: 'What would settle it: your choice between these. The research did not decide it, so what '
    + 'is needed is your judgement about which risk is worth taking — not a further search. Choose '
    + 'in the panel, or edit the field in your own words.',
  field: 'What would settle it: accept it, edit it in your own words, or reject it — in the panel. '
    + 'Nothing here is settled until you say so.',
  cause: 'What would settle it: say which of these are material (remove it and the problem largely '
    + 'goes) and which merely contribute, and strike any that are wrong. Your knowledge of the '
    + 'people and the incentives beats the record here.',
  approach: 'What would settle it: choose one approach and rule the others out with a reason — '
    + 'a policy that rules nothing out is not a choice.',
  gapResearch: 'What would settle it: a source that answers it. If you hold one, attach it to the '
    + 'idea; otherwise say so and Lex searches again on the next build with everything you have '
    + 'added.',
  gapLimitation: 'What would settle it: the search itself did not complete, so this is our gap, not '
    + 'a finding. A re-run repeats the search; nothing is needed from you except the re-run.',
  gapOnlyYou: 'What would settle it: only you can answer this — add what you know in the panel and '
    + 're-run.',
  testimony: 'What would settle it: your account, in the panel — what you have seen, what the '
    + 'paperwork does not show, what you have already ruled out — and then a re-run, so the next '
    + 'pass searches on it.',
  challenge: 'What would settle it: a response. Accept it and change the draft, or dismiss it with '
    + 'a reason — in the panel. A dismissed challenge stays on the record with your reason beside it.',
} as const

const RESOLVE_MARK = 'What would settle it:'

interface Snapshot {
  buildId: string
  buildVersion: number
  composedAt: Date
  /** TRUE when composed after the build, from rows that may have moved since. */
  composedLate: boolean
  body: string
  counts: { decisions: number; causes: number; approaches: number; gaps: number; testimony: number; challenges: number }
}

const KERNEL_PAGE_KEYS = new Set(PAGE_SEQUENCE.filter((p) => p.key !== 'ORIENTATION').map((p) => p.key))
const KERNEL_FIELD_KEYS = new Set(
  PAGE_SEQUENCE.filter((p) => KERNEL_PAGE_KEYS.has(p.key)).flatMap((p) => p.fields.map((f) => f.key)),
)
const fieldLabel = (key: string): string => ALL_FIELDS.find((f) => f.key === key)?.label ?? readableForkKey(key)

function oneLine(v: unknown, cap = 600): string {
  const t = typeof v === 'string' ? v : JSON.stringify(v ?? '')
  return t.replace(/\s+/g, ' ').trim().slice(0, cap)
}

/** The proposal on a field, as one line, whatever shape the field stores. */
function proposalText(proposal: unknown): string {
  if (!proposal || typeof proposal !== 'object') return ''
  const v = (proposal as { value?: unknown }).value
  if (typeof v === 'string') return oneLine(v)
  if (Array.isArray(v)) return oneLine(v.map((x) => (typeof x === 'string' ? x : JSON.stringify(x))).join('; '))
  if (v && typeof v === 'object') {
    return oneLine(Object.entries(v as Record<string, unknown>)
      .filter(([, x]) => typeof x === 'string' && x.trim())
      .map(([k, x]) => `${k}: ${x}`).join(' · '))
  }
  return ''
}

/**
 * §3's classification, from the producer's own `why` sentence — the stored row drops `kind`
 * (`readKnownUnknowns` keeps question and why only), so the sentence the producer wrote is
 * the surviving tag. These are the producers' literal strings, not a reading of the prose.
 */
function gapRoute(g: KnownUnknown): { kind: string; resolves: string } {
  const why = g.why || ''
  if (/failed to run|did not complete|failed after retrieval/i.test(why)) {
    return { kind: 'the search did not complete (our limitation)', resolves: RESOLVES.gapLimitation }
  }
  if (/only you|the person holding|could not be read/i.test(why)) {
    return { kind: 'only you can supply this', resolves: RESOLVES.gapOnlyYou }
  }
  if (/named by the (question|pass) as unfindable/i.test(why)) {
    return { kind: 'the pass looked and named this as absent from what it retrieved', resolves: RESOLVES.gapResearch }
  }
  return { kind: 'nothing retrieved answered it', resolves: RESOLVES.gapResearch }
}

/** Compose the markdown body from the build's rows. Pure read; writes nothing. */
export async function composeInitialQuestions(ideaId: string, buildId: string, buildVersion: number, opts: { late: boolean }): Promise<Snapshot> {
  const [build, forks, fields, causes, options, passes, issues, elicitation] = await Promise.all([
    prisma.ideaBuild.findUnique({ where: { id: buildId }, select: { uncertainties: true, completedAt: true, startedAt: true } }),
    prisma.buildFork.findMany({ where: { buildId }, orderBy: [{ forkKey: 'asc' }, { alternativeIndex: 'asc' }] }),
    prisma.ideaFieldState.findMany({ where: { ideaId, status: 'AWAITING_CONFIRMATION' }, select: { fieldKey: true, proposal: true } }),
    prisma.diagnosisCause.findMany({ where: { ideaId }, orderBy: { createdAt: 'asc' }, select: { cause: true, classification: true, isRootCause: true, whyPersisted: true, source: true } }),
    prisma.policyOption.findMany({ where: { ideaId }, orderBy: { orderIndex: 'asc' }, select: { approach: true, caseFor: true, caseAgainst: true, status: true, ruleOutReason: true } }),
    prisma.deepeningPass.findMany({ where: { ideaId, runVersion: buildVersion }, select: { passKey: true, status: true, failureReason: true, knownUnknowns: true } }),
    prisma.deepeningIssue.findMany({ where: { ideaId, runVersion: buildVersion }, orderBy: { createdAt: 'asc' }, select: { title: true, text: true, status: true, passKey: true, sourceModel: true, dismissReason: true } }),
    prisma.ideaElicitation.findUnique({ where: { ideaId }, select: { ownKnowledge: true, ruledOut: true, readingUrl: true, readingFileName: true, readingStatus: true, goalDetail: true } }),
  ])
  if (!build) throw new ExportUnavailableError('That build no longer exists.')

  const md: string[] = []
  const counts = { decisions: 0, causes: 0, approaches: 0, gaps: 0, testimony: 0, challenges: 0 }

  // ── 1. Decisions awaiting them ────────────────────────────────────────────
  md.push('## Decisions waiting on you')
  const byFork = new Map<string, typeof forks>()
  for (const f of forks) byFork.set(f.forkKey, [...(byFork.get(f.forkKey) ?? []), f])
  const openForks = [...byFork.entries()].filter(([, rows]) => !rows[0].resolved)
  if (openForks.length) {
    md.push('', 'Each of these is a fork Lex took one way and could have taken another. The road taken is '
      + 'the draft; what it rules out is the alternative beside it.')
    for (const [forkKey, rows] of openForks) {
      counts.decisions++
      md.push('', `**${fieldLabel(rows[0].fieldKey)} — ${readableForkKey(forkKey)}.** Lex chose: ${oneLine(rows[0].chosen)}`)
      if (rows[0].recommendationReason?.trim()) md.push(`Why: ${oneLine(rows[0].recommendationReason)}`)
      for (const r of rows) {
        md.push(`- Taking this rules out: ${oneLine(r.alternative)} — ${oneLine(r.caseForAlternative)}`)
      }
      md.push(RESOLVES.fork)
    }
  }
  const awaiting = fields.filter((f) => KERNEL_FIELD_KEYS.has(f.fieldKey))
  if (awaiting.length) {
    md.push('', '**Kernel fields drafted and not yet settled.** Each is a proposal until you accept it, '
      + 'and accepting one commits the fields after it to being read against it.')
    for (const f of awaiting) {
      counts.decisions++
      const text = proposalText(f.proposal)
      md.push('', `- **${fieldLabel(f.fieldKey)}**${text ? ` — ${text}` : ' — (drafted; see the panel)'}`)
      md.push(`  ${RESOLVES.field}`)
    }
  }
  if (!openForks.length && !awaiting.length) md.push('', 'Nothing here is waiting on you — every decision point this build raised has been settled.')

  // ── 2. Choices between causes, and between candidate approaches ───────────
  md.push('', '## Choices between causes, and between approaches')
  if (causes.length) {
    md.push('', '**Causes.** Drafted by Lex where marked; the classification is a proposal.')
    for (const c of causes) {
      counts.causes++
      const cls = c.classification === 'MATERIAL' ? 'material' : c.classification === 'CONTRIBUTORY' ? 'contributory' : 'not yet classified'
      md.push(`- ${c.isRootCause ? 'Root cause — ' : ''}${oneLine(c.cause)} *(${cls}${c.source === 'LEX_CORPUS' ? ', drafted by Lex' : ''})*`
        + (c.whyPersisted?.trim() ? ` Why it has persisted: ${oneLine(c.whyPersisted)}` : ''))
    }
    md.push(RESOLVES.cause)
  }
  if (options.length) {
    md.push('', '**Candidate approaches.**')
    for (const o of options) {
      counts.approaches++
      const st = o.status === 'CHOSEN' ? 'chosen by Lex' : o.status === 'RULED_OUT' ? `ruled out${o.ruleOutReason ? ` — ${oneLine(o.ruleOutReason)}` : ''}` : 'candidate'
      md.push(`- ${oneLine(o.approach)} *(${st})*`
        + (o.caseFor?.trim() ? ` For: ${oneLine(o.caseFor, 300)}` : '')
        + (o.caseAgainst?.trim() ? ` Against: ${oneLine(o.caseAgainst, 300)}` : ''))
    }
    md.push(RESOLVES.approach)
  }
  if (!causes.length && !options.length) md.push('', 'This build drafted no causes and no candidate approaches to choose between.')

  // ── 3. What the corpus could not answer ───────────────────────────────────
  md.push('', '## What the corpus could not answer')
  const gaps = collapseKnownUnknowns(passes.flatMap((p) => readKnownUnknowns(p.knownUnknowns)))
  const failed = passes.filter((p) => p.status === 'FAILED')
  if (gaps.length || failed.length) {
    md.push('', 'Each gap says what kind of gap it is, because "we looked and found nothing" and "our search '
      + 'did not run" are different facts and only one of them is about the record.')
    for (const g of gaps) {
      counts.gaps++
      const r = gapRoute(g)
      md.push('', `- **${oneLine(g.question, 300)}** — *${r.kind}.* ${oneLine(g.why, 300)}`)
      md.push(`  ${r.resolves}`)
    }
    for (const p of failed) {
      counts.gaps++
      md.push('', `- **${readableForkKey(p.passKey)}** — *the search did not complete (our limitation).* ${oneLine(p.failureReason ?? '')}`)
      md.push(`  ${RESOLVES.gapLimitation}`)
    }
  } else {
    md.push('', 'The research pass reported no unanswered question on this build.')
  }

  // ── 4. What you know that we do not ───────────────────────────────────────
  md.push('', '## What you know that we do not')
  const unc = (build.uncertainties && typeof build.uncertainties === 'object' && !Array.isArray(build.uncertainties))
    ? Object.entries(build.uncertainties as Record<string, string>).filter(([, v]) => typeof v === 'string' && v.trim())
    : []
  const testimonyGaps: string[] = []
  if (!elicitation?.ownKnowledge?.trim()) {
    testimonyGaps.push('You gave no first-hand account at the start — what you have seen, been told, or know '
      + 'the paperwork does not show. Every draft above was written from the record alone.')
  }
  if (!elicitation?.ruledOut?.trim()) {
    testimonyGaps.push('You have not said what you have already ruled out, so Lex may propose things you have '
      + 'already decided against.')
  }
  if ((elicitation?.readingUrl || elicitation?.readingFileName) && elicitation.readingStatus === 'NOT_READ') {
    testimonyGaps.push(`You named ${elicitation.readingFileName ? `"${elicitation.readingFileName}"` : elicitation.readingUrl} `
      + 'and it was not read — nothing in this build comes from it. Attach it and it is read on the next build.')
  }
  if (testimonyGaps.length || unc.length) {
    for (const t of testimonyGaps) {
      counts.testimony++
      md.push('', `- ${t}`, `  ${RESOLVES.testimony}`)
    }
    if (unc.length) {
      md.push('', '**Where Lex is least sure, field by field** — these are the places your knowledge would change the draft most:')
      for (const [k, sentence] of unc) {
        counts.testimony++
        md.push('', `- **${fieldLabel(k)}** — ${oneLine(sentence, 400)}`, `  ${RESOLVES.testimony}`)
      }
    }
  } else {
    md.push('', 'Lex recorded no field it was unsure of, and your account, your ruled-outs and your reading are all on the idea.')
  }

  // ── 5. Challenges that need a response ────────────────────────────────────
  md.push('', '## Challenges that need a response')
  const open = issues.filter((i) => i.status === 'OPEN')
  const settled = issues.filter((i) => i.status !== 'OPEN')
  if (open.length) {
    for (const i of open) {
      counts.challenges++
      md.push('', `- ${i.title?.trim() ? `**${oneLine(i.title, 160)}** — ` : ''}${oneLine(i.text, 700)}`
        + (i.sourceModel ? ` *(raised by ${i.sourceModel}${i.passKey ? `, ${readableForkKey(i.passKey)}` : ''})*` : ` *(${readableForkKey(i.passKey)})*`))
      md.push(`  ${RESOLVES.challenge}`)
    }
  } else {
    md.push('', issues.length ? 'Every challenge this build raised has been answered.' : 'This build raised no challenge against the proposal.')
  }
  if (settled.length && opts.late) {
    md.push('', `*${settled.length} challenge${settled.length === 1 ? '' : 's'} from this build ${settled.length === 1 ? 'has' : 'have'} already been answered since, and ${settled.length === 1 ? 'is' : 'are'} not listed as open.*`)
  }

  return {
    buildId, buildVersion,
    composedAt: new Date(),
    composedLate: opts.late,
    body: md.join('\n'),
    counts,
  }
}

function summaryLine(s: Snapshot): string {
  const c = s.counts
  return `${c.decisions} decision${c.decisions === 1 ? '' : 's'} waiting · ${c.causes} cause${c.causes === 1 ? '' : 's'} and ${c.approaches} approach${c.approaches === 1 ? '' : 'es'} to choose between · ${c.gaps} gap${c.gaps === 1 ? '' : 's'} · ${c.testimony} thing${c.testimony === 1 ? '' : 's'} only you can supply · ${c.challenges} challenge${c.challenges === 1 ? '' : 's'} to answer`
}

/**
 * Write the snapshot for a build that has just settled. Called from `finishBuild`. Replaces
 * any snapshot from an earlier build — the pair always describes the LATEST build, exactly
 * as the briefing does.
 */
export async function snapshotInitialQuestions(ideaId: string, buildId: string, buildVersion: number): Promise<void> {
  const s = await composeInitialQuestions(ideaId, buildId, buildVersion, { late: false })
  await prisma.document.upsert({
    where: { ideaId_kind: { ideaId, kind: INITIAL_QUESTIONS_KIND } },
    create: { ideaId, kind: INITIAL_QUESTIONS_KIND, status: 'ready', summary: summaryLine(s), body: s.body, buildId, buildVersion },
    update: { status: 'ready', summary: summaryLine(s), body: s.body, buildId, buildVersion },
  })
  console.log('[lex-diag] initial questions snapshot written', { ideaId, buildId, buildVersion, ...s.counts })
}

/**
 * The stored snapshot for the latest DONE build — composed now if that build has none.
 *
 * ⚠ LAZY COMPOSITION IS LABELLED. A snapshot composed after the build is from rows that may
 * have moved (forks resolved, challenges answered), and the document says "composed on <date>
 * from the build's rows as they stood then" rather than claiming it was frozen at the build.
 */
export async function ensureInitialQuestions(ideaId: string): Promise<{
  body: string; summary: string | null; buildId: string; buildVersion: number; updatedAt: Date; composedLate: boolean
}> {
  const latest = await prisma.ideaBuild.findFirst({
    where: { ideaId, status: 'DONE' }, orderBy: { version: 'desc' }, select: { id: true, version: true, completedAt: true },
  })
  if (!latest) throw new ExportUnavailableError('There is no completed build on this idea yet, so there are no questions to list.')

  const doc = await prisma.document.findUnique({
    where: { ideaId_kind: { ideaId, kind: INITIAL_QUESTIONS_KIND } },
    select: { body: true, summary: true, buildId: true, buildVersion: true, updatedAt: true, status: true },
  })
  if (doc?.body && doc.buildId === latest.id && doc.status === 'ready') {
    // Composed at the build's end if the row was written within a few minutes of it settling;
    // otherwise it was composed on a later read.
    const late = !latest.completedAt || (doc.updatedAt.getTime() - latest.completedAt.getTime()) > 10 * 60 * 1000
    return { body: doc.body, summary: doc.summary, buildId: latest.id, buildVersion: latest.version, updatedAt: doc.updatedAt, composedLate: late }
  }

  const s = await composeInitialQuestions(ideaId, latest.id, latest.version, { late: true })
  const written = await prisma.document.upsert({
    where: { ideaId_kind: { ideaId, kind: INITIAL_QUESTIONS_KIND } },
    create: { ideaId, kind: INITIAL_QUESTIONS_KIND, status: 'ready', summary: summaryLine(s), body: s.body, buildId: latest.id, buildVersion: latest.version },
    update: { status: 'ready', summary: summaryLine(s), body: s.body, buildId: latest.id, buildVersion: latest.version },
    select: { updatedAt: true },
  })
  console.log('[lex-diag] initial questions composed late, on read', { ideaId, buildId: latest.id, buildVersion: latest.version, ...s.counts })
  return { body: s.body, summary: summaryLine(s), buildId: latest.id, buildVersion: latest.version, updatedAt: written.updatedAt, composedLate: true }
}

export interface QuestionsBuildResult {
  model: DocumentModel
  fingerprint: string
  sourceLabel: string
}

/** Build the document model from the STORED snapshot. Never recomposes. */
export async function buildInitialQuestions(ideaId: string): Promise<QuestionsBuildResult> {
  const idea = await prisma.idea.findUnique({ where: { id: ideaId }, select: { title: true } })
  if (!idea) throw new ExportUnavailableError('That idea no longer exists.')
  const snap = await ensureInitialQuestions(ideaId)
  const build = await prisma.ideaBuild.findUnique({ where: { id: snap.buildId }, select: { completedAt: true, startedAt: true } })
  const when = build?.completedAt ?? build?.startedAt ?? snap.updatedAt

  const blocks: Block[] = []
  const dot = INITIAL_QUESTIONS_OPENING.indexOf('. ') + 1
  blocks.push({ kind: 'paragraph', runs: [
    { text: INITIAL_QUESTIONS_OPENING.slice(0, dot), bold: true },
    { text: INITIAL_QUESTIONS_OPENING.slice(dot) },
  ] })
  blocks.push({ kind: 'paragraph', runs: [{
    text: snap.composedLate
      ? `A record of what build ${snap.buildVersion} of this idea needed from you, composed on `
        + `${snap.updatedAt.toISOString().slice(0, 16).replace('T', ' ')} UTC from that build's rows as they stood then. `
        + 'It does not change as you work: the live list is the worklist on the idea.'
      : `A record of what build ${snap.buildVersion} of this idea needed from you, frozen when the build finished `
        + `on ${when.toISOString().slice(0, 16).replace('T', ' ')} UTC. It does not change as you work: the live list `
        + 'is the worklist on the idea.',
    italic: true,
  }] })
  blocks.push(...betaBlocks())
  if (snap.summary?.trim()) blocks.push({ kind: 'note', text: snap.summary.trim() })
  blocks.push(...markdownToBlocks(snap.body))

  const sourceLabel = [
    `build ${snap.buildVersion} of this idea (${when.toISOString().slice(0, 16).replace('T', ' ')} UTC)`,
    'the stored Initial Questions snapshot',
  ].join(', ')

  const fingerprint = createHash('sha256')
    .update(JSON.stringify({ layout: LAYOUT_VERSION, title: idea.title, body: snap.body, summary: snap.summary ?? '', buildId: snap.buildId, buildVersion: snap.buildVersion }))
    .digest('hex')

  return {
    model: {
      title: INITIAL_QUESTIONS_NAME,
      subtitle: `${idea.title || 'Untitled idea'} · ${BETA_MARKER}`,
      sourceLabel,
      generatedAt: new Date(),
      blocks,
    },
    fingerprint,
    sourceLabel,
  }
}

/** Every rendered item carries a route — the assertion `check:export` runs on a composed body. */
export function itemsWithoutRoute(body: string): string[] {
  const out: string[] = []
  const lines = body.split('\n')
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (!/^\s*- /.test(line)) continue
    // an item's route is the next non-empty line that carries the mark, before the next item/heading
    let j = i + 1
    let found = false
    while (j < lines.length && !/^\s*- /.test(lines[j]) && !/^## /.test(lines[j])) {
      if (lines[j].includes(RESOLVE_MARK)) { found = true; break }
      j++
    }
    // items inside a fork block share the fork's single route line, which follows the last item
    if (!found) {
      // look back for a fork block: a "**…** Lex chose:" line above with a route after the block
      let k = i - 1
      while (k >= 0 && !/^## /.test(lines[k]) && !/Lex chose:/.test(lines[k])) k--
      if (k >= 0 && /Lex chose:/.test(lines[k])) {
        let m = i + 1
        while (m < lines.length && !/^## /.test(lines[m]) && !/Lex chose:|^\*\*Kernel fields/.test(lines[m])) {
          if (lines[m].includes(RESOLVE_MARK)) { found = true; break }
          m++
        }
      }
    }
    // cause / approach lists share one route line after the list
    if (!found) {
      let m = i + 1
      while (m < lines.length && !/^## /.test(lines[m]) && !/^\*\*Candidate approaches|^\*\*Causes/.test(lines[m])) {
        if (lines[m].includes(RESOLVE_MARK)) { found = true; break }
        m++
      }
    }
    if (!found) out.push(line.trim().slice(0, 120))
  }
  return out
}
